### ISSUE TITLE
Shooter example produces a blank screen / crashes

### ISSUE THREAD

**Issue by SolviQorda** [Mokosha/Lambency#17]
Loading the shooter example through ghci loaded a non-responsive window, which crashed when I attempted key input.

**Comment by Mokosha** [comment]
Hi, I took a look into this. This doesn't seem to be a problem for this repo. I can't open a window via GLFW from GHCi at all:

    Prelude> import qualified Graphics.UI.GLFW as GLFW
    Prelude GLFW> GLFW.init
    True
    Prelude GLFW> GLFW.createWindow 100 100 "Test" Nothing Nothing
    ** Assertion failed... crash etc **

For me on OS X it crashes due to some `NSInternalInconsistencyException` in `NSUndoManager`. If this is crucial to you workflow, feel free to open a bug on [`bindings-GLFW`](https://www.github.com/bsl/bindings-GLFW), as it exists at that level.
